version: '3.8'
services:
  database:
    image: postgres:16.8
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD={some-pass}
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - /Users/yagyesh_tripathi/pgdata:/var/lib/postgresql/data
    command: [ "postgres", "-c", "wal_level=logical" ]
  zookeeper:
    image: zookeeper:3.9.0
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  kafka:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093
    depends_on:
      - zookeeper
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
      - KAFKA_CLUSTERS_0_SCHEMA_REGISTRY=http://localhost:8081
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "9001:8080"
    depends_on:
      - kafka
  schema-registry:
    image: confluentinc/cp-schema-registry:7.9.1
    depends_on:
      - kafka
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
      SCHEMA_REGISTRY_HOST_NAME: localhost
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8082
    ports:
      - "8082:8082"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.ml.enabled=false
      - xpack.security.http.ssl.enabled=false
      - ingest.geoip.downloader.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - /Users/yagyesh_tripathi/esdata:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
  connect:
    image: debezium/connect:2.4.0.Final
    ports:
      - 8083:8083
      - 8778:8778
    links:
      - kafka
      - database
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=connector_group_1
      - CONFIG_STORAGE_TOPIC=debezium_configs
      - OFFSET_STORAGE_TOPIC=debezium_offsets
      - STATUS_STORAGE_TOPIC=debezium_statuses
      - LOG_LEVEL=DEBUG
  setup-debezium-connector:
    image: curlimages/curl
    depends_on:
      - connect
    links:
      - connect
    environment:
      DEBEZIUM_CONFIG: |
        {
          "name": "postgresql-connector",
          "config": {
            "connector.class": "io.debezium.connector.postgresql.PostgresConnector",
            "connector.displayName": "PostgreSQL",
            "topic.prefix": "pg-changes",
            "database.user": "postgres",
            "database.dbname": "postgres",
            "database.hostname": "database",
            "database.password": "{some-pass}",
            "name": "postgresql-connector",
            "connector.id": "postgres",
            "plugin.name": "pgoutput",
            "snapshot.mode":"initial",
            "table.include.list": "public.movies,public.genres,public.movie_genre,public.belongs_to_collections,public.production_companies,public.persons"
          } 
        }
    command: >
      sh -c "
        sleep 10;
        echo Waiting for Kafka Connect to start listening on connect:8083...;
        while ! nc -z connect 8083;
        do
          sleep 1;
        done;
        echo Kafka Connect is up!;
        echo $$DEBEZIUM_CONFIG > /tmp/debezium-connector-config.json
        curl -X POST -H \"Content-Type: application/json\" --data @/tmp/debezium-connector-config.json http://connect:8083/connectors;
      "