spring:
  application:
    name: movie-producer
    max-in-memory:
      size: "524288" # 512KB
  kafka:
    producer:
      bootstrap-servers: "localhost:9093"
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer"
      properties:
        schema.registry.url: "http://localhost:8082"
rapid-api:
  key: "{key}"
  host: "imdb236.p.rapidapi.com"
tmdb:
  api:
    key: "{some_key}"
  base:
    url: "https://api.themoviedb.org/3"
kafka:
  topic:
      top250: "top-250"
      genre: "genres"
server:
  port: 8089

schema:
  registry:
    url: "http://localhost:8081"
